### PR TITLE
Update jshn.c

### PR DESCRIPTION
**Pull request by thefat32**
When trying to compile on Ubuntu 14.04 got:

[ 51%] Building C object CMakeFiles/jshn.dir/jshn.c.o
/opt/git/libubox/jshn.c: In function ‘jshn_parse’:
/opt/git/libubox/jshn.c:162:2: warning: implicit declaration of function ‘is_error’ [-Wimplicit-function-declaration]
  if (is_error(obj) || json_object_get_type(obj) != json_type_object) {
  ^

adding #include json/bits.h solve the problem (You must have json-c sources on "/usr/include/json") for this to function.

### CODE REVIEW

**Comment by xfguo** [comment]
Hi, @lukss12 , you should commit you patch to the mail list of OpenWrt-Dev, https://lists.openwrt.org/cgi-bin/mailman/listinfo/openwrt-devel.
