### PR TITLE
Update blobmsg_json.c

### PR DESCRIPTION
**Pull request by thefat32**
When trying to compile on Ubuntu 14.04 got:

[ 48%] Building C object CMakeFiles/blobmsg_json.dir/blobmsg_json.c.o
/opt/git/libubox/blobmsg_json.c: In function ‘__blobmsg_add_json’:
/opt/git/libubox/blobmsg_json.c:78:2: error: implicit declaration of function ‘is_error’ [-Werror=implicit-function-declaration]
  if (is_error(obj))
  ^

adding #include json/bits.h solve the problem (You must have json-c sources on "/usr/include/json") for this to function.

### CODE REVIEW

**Comment by xfguo** [comment]
Hi, @lukss12 , you should commit you patch to the mail list of OpenWrt-Dev, https://lists.openwrt.org/cgi-bin/mailman/listinfo/openwrt-devel.
